# Generated by Django 4.2.2 on 2023-08-15 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='metric_system',
            new_name='unit',
        ),
    ]
